#############################################################################
# Makefile for building: adt_aec
# Generated by qmake (2.01a) (Qt 4.8.5) on: ?? 4? 27 09:38:23 2017
# Project:  adt_aec.pro
# Template: app
# Command: /opt/poky/1.5.3/sysroots/x86_64-pokysdk-linux/usr/bin/qmake -spec /opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile adt_aec.pro
#############################################################################

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -pipe $(OE_QMAKE_CFLAGS) -DLINUX=1 -DEGL_API_FB=1 -g -g -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -pipe -pipe $(OE_QMAKE_CFLAGS) -DLINUX=1 -DEGL_API_FB=1 $(OE_QMAKE_CXXFLAGS) -g -g -g -Wall -W -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/linux-g++ -I. -I$(OE_QMAKE_INCDIR_QT)/QtCore -I$(OE_QMAKE_INCDIR_QT) -Icommon/include -Iinclude -I/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include -I.
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-rpath-link,$(OE_QMAKE_LIBDIR_QT)
LIBS          = $(SUBLIBS)  -L$(OE_QMAKE_LIBDIR_QT) -L./lib -lADT_AECG4_cortex-a9_V5_04_03_hf_fpic -ladt_agc_v3_07_01_hf_fpic -ladt_nr2_V3_04_hf_fpic -L/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib -lasound -lQtCore -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /opt/poky/1.5.3/sysroots/x86_64-pokysdk-linux/usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/unix.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/linux.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/qconfig.pri \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt_config.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/default_pre.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/debug.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/default_post.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/shared.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/warn_on.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/moc.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/resources.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/uic.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/yacc.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/lex.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		adt_aec.pro
QMAKE_TARGET  = adt_aec
DESTDIR       = 
TARGET        = adt_aec

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: adt_aec.pro  /opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/linux-g++/qmake.conf /opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/unix.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/linux.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/qconfig.pri \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt_config.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/default_pre.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/debug.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/default_post.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/shared.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/warn_on.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/moc.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/resources.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/uic.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/yacc.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/lex.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQtCore.prl
	$(QMAKE) -spec /opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile adt_aec.pro
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/unix.conf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/linux.conf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/gcc-base.conf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/common/g++-unix.conf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/qconfig.pri:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt_functions.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt_config.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/default_pre.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/debug.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/default_post.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/shared.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/warn_on.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/qt.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/unix/thread.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/moc.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/resources.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/uic.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/yacc.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/lex.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/poky/1.5.3/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile adt_aec.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/adt_aec1.0.0 || $(MKDIR) .tmp/adt_aec1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/adt_aec1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/adt_aec1.0.0/ && (cd `dirname .tmp/adt_aec1.0.0` && $(TAR) adt_aec1.0.0.tar adt_aec1.0.0 && $(COMPRESS) adt_aec1.0.0.tar) && $(MOVE) `dirname .tmp/adt_aec1.0.0`/adt_aec1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/adt_aec1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/aec/ || $(MKDIR) $(INSTALL_ROOT)/opt/aec/ 
	-$(INSTALL_PROGRAM) /home/rudy/workspace/qt4/ADT/adt_aec/adt_aec $(INSTALL_ROOT)/opt/aec/


uninstall_target:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/aec/adt_aec
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/aec/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

